#!/bin/bash

# Speed up script by turning off history?

# Function to display description of script
function show_description() {
    echo "This script first enumerates all secrets to pick from. Run as-is"
}

# Function to display help menu
function show_usage() {
#  echo script name without path
    echo "Usage: ${0##*/} [OPTION]..."
    echo "====================="
    echo "Options:"
    echo "  -h, --help          Show Description"
    echo "  -v, --version       Show Version"
    echo "  -hw, --hello-world  Print Hello World"
}

# Parse command-line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            show_description
            exit 0
            ;;
        -u|--usage)
            show_usage
            exit 0
            ;;
        -v|--version)
            echo "Version 0.1 - initial version"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "See '$0 --help' for usage."
            exit 1
            ;;
    esac
done


# +++++ add payload here +++++
profiles_list=$(grep '\[profile' ~/.aws/config | grep -v "sie-cloud-laco-sandbox-nonprod" | grep -v "sie-cloud-laco-cp-prod" | awk '{print $2}' | tr -d ']')
echo "Select an AWS profile:"
select profile in $profiles_list; do
  break
done

echo "Selected profile: $profile"

secrets=($(aws secretsmanager list-secrets --profile $profile --query "SecretList[?starts_with(Name, 'pde-')].{Name: Name}" --output text))

# Display the enumerated list of secrets
echo "Available secrets:"
for i in "${!secrets[@]}"; do
    echo "$i. ${secrets[i]}"
done

# Prompt user to choose an option
read -p "Enter the number of the secret to choose: " choice

# Validate the user's choice
if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 0 )) && (( choice < ${#secrets[@]} )); then
    chosen_secret="${secrets[choice]}"
    echo "You selected: $chosen_secret"
    secret_value=$(aws secretsmanager get-secret-value --profile $profile --secret-id $chosen_secret --query SecretString --output text)
    echo "Secret value: $secret_value"
else
    echo "Invalid choice. Exiting."
    exit 1
fi

# +++++ add payload here +++++

